# Generated by Django 5.1.5 on 2025-01-27 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_model', models.CharField(max_length=255, unique=True)),
                ('aircraft_capacity', models.IntegerField()),
                ('aircraft_manufacturer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=255)),
                ('airline_code', models.CharField(max_length=10, unique=True)),
                ('airline_rules', models.TextField()),
                ('airline_logo', models.ImageField(blank=True, null=True, upload_to='airline_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=255)),
                ('airport_code', models.CharField(max_length=10, unique=True)),
                ('airport_city', models.CharField(max_length=255)),
                ('airport_country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, unique=True)),
                ('flight_type', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=15)),
                ('trip_type', models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], max_length=15)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_datetime', models.DateTimeField()),
                ('cabin_type', models.CharField(choices=[('economy', 'Economy'), ('business', 'Business Class'), ('first', 'First Class')], max_length=20)),
                ('base_price', models.BigIntegerField()),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('baggage_limit_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight_rules', models.TextField()),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flight.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flight.airline')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='Flight.airport')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='Flight.airport')),
            ],
        ),
    ]
