# Generated by Django 5.1.5 on 2025-01-31 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
