# Generated by Django 5.1.5 on 2025-01-31 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0002_flight_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='final_price',
            field=models.BigIntegerField(),
        ),
    ]
