# Generated by Django 5.1.5 on 2025-02-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flight', '0003_alter_flight_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='cabin_type',
            field=models.CharField(choices=[('ECONOMY', 'Economy'), ('BUSINESS', 'Business Class'), ('FIRST', 'First Class')], max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_type',
            field=models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], max_length=15),
        ),
        migrations.AlterField(
            model_name='flight',
            name='trip_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('INDIRECT', 'Indirect')], max_length=15),
        ),
    ]
